name: repo-sync manual
on:
 # schedule:
 #   - cron:  '0/5 * * * *'
  workflow_dispatch:
  pull_request:
  push:
     branches:
       - main

#permissions:
#  contents: read
#  pull-requests: read


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Git Sync Alternate
    #  uses: actions/checkout@v3
    
      run: git clone --bare https://gitsrinuhub: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@github.com/gitsrinuhub/originalrepo.git
    - run: git config --global user.name "srinivas"
    - run: git config --global user.email "srinivas.mungoti@sapper.ai"
    - run: git remote set-url --push origin https://srinivas3000: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@github.com/srinivas3000/testrepo.git
    - run: cd originalrepo.git
    - run: git push --mirror 
    - run: cd ..
    - run: rm -rf originalrepo.git
   # - run: git remote set-url --push origin https://srinivas3000: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@github.com/srinivas3000/testrepo.git
   # - run: git fetch -p origin
   # - run: git push --mirror
    
 #  - run: git remote update
 #   - run: git push --mirror
